---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Network automation and Sources of Truth"
      solveButton: false
    - name: module-02
      label: "AAP Dynamic Inventory"
      solveButton: false
    - name: module-03
      label: "Event-Driven Ansible: Automation Decisions"
      solveButton: false
    - name: module-04
      label: "Event-Driven Ansible Rulebooks"
      solveButton: false
    - name: module-05
      label: "Event-Driven Ansible Playbooks"
      solveButton: false
    - name: module-06
      label: "Event-Driven Ansible: New Device Added Workflow"
      solveButton: false
    - name: module-07
      label: "Event-Driven Ansible and NetBox in Action"
      solveButton: false

tabs:
  - name: Ansible Automation Platform
    url: https://control-${guid}.${domain}/
  - name: Netbox
    url: https://netbox-${guid}.${domain}
    external: false
  - name: gitea
    url: https://gitea-${guid}.${domain}/
  - name: VS Ccode
    url: https://vscode-${guid}.${domain}
    external: false
  - name: ">_Terminal"
    url: /wetty_devtools
    secondary_name: ">_Netbox"
    secondary_url: /wetty_netbox   
